# ==========  TPM  ==========
set -g @plugin 'tmux-plugins/tpm'


# ==========  Basic Settings  ==========
set -g default-shell "/usr/bin/zsh"  # Set zsh to default shell
set -g mouse on                      # Mouse resize, select pane, select window, right click menu
set-window-option -g mode-keys vi    # Search mode vi
set -g default-terminal screen-256color  # Set to allow for vim-airline to display properly
set -g history-limit 50000
#set -g allow-rename off

# Keybinds
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind  r  source-file ~/.tmux.conf \; display-message "Config reloaded..."  # Reload Tmux config
bind  h  select-pane -L  # Vi keys to select panes, C-b h to select to the left
bind  j  select-pane -D  # C-b j
bind  k  select-pane -U  # C-b k
bind  l  select-pane -R  # C-b l
bind M-j command-prompt -p "Join pane from: "  "join-pane -s '%%'"  # Join / send panes to windows
bind M-s command-prompt -p "Send pane to: "  "join-pane -t '%%'"


# ==========  Theme  ==========
#source-file "$HOME/.local/share/tmux/theme-pack-jimeh/basic.tmuxtheme"  # tmux theme
set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true       # Powerline arrows for sections
set -g @dracula-border-contrast true      # High contrast seperator for panes
#set -g @dracula-show-left-sep 
#set -g @dracula-show-right-sep 
set -g @dracula-show-flags true           # * flag indicating active window
set -g @dracula-show-left-icon ' #S |  #W |  #P'  # #H hostname, #h host no domain, #S session, #W window
set -g @dracula-left-icon-padding 0       # Padding for left icon section

# Dracula section plugins
set -g @dracula-plugins 'network-vpn time'  # Plugin sections list
set -g @dracula-show-timezone false
set -g @dracula-time-format '  %a %m/%d %R'
set -g @dracula-network-vpn-verbose true
set -g @dracula-network-vpn-label "󰒄 "


# ==========  Tmux Logging  ==========
# prefix + shift + p        -- log current pane start/stop
# prefix + alt + shift + p  -- save complete pane history
set -g @plugin 'tmux-plugins/tmux-logging'  # save dir ~/.local/share/tmux/resuurect


# ==========  Tmux Resurrect  ==========
# prefix + ctrl + s  -- save current environment/windows/panes
# prefix + ctrl + r  -- restore environment
set -g @plugin 'tmux-plugins/tmux-resurrect'


# ==========  Tmux Yank  ==========
# Yank to clipboard from Tmux copy mode (C-b [)
# Enter copy mode, mmux copy modeark text with space, then y
set -g @plugin 'tmux-plugins/tmux-yank'
bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"


# ==========  Vim Tmux Navigator  ==========
# https://github.com/christoomey/vim-tmux-navigator
# Allows for Ctrl-h/j/k/l movement seamlessly between Vim and Tmux
set -g @plugin 'christoomey/vim-tmux-navigator'


# ==========  Tmux Fzf  ==========
# prefix + shift + f  -- Open Tmux Fzf
# [shift +] tab       -- Un/Mark multiple items
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_OPTIONS="-p --reverse"


# Initialize TPM, keep at bottom
run '/usr/share/tmux-plugin-manager/tpm'
